<?php

namespace Database\Seeders;

use App\Models\CustomerBasic;
use Illuminate\Database\Seeder;

class CustomerBasicSeeder extends Seeder
{
    public function run(): void
    {
        CustomerBasic::query()->delete();

        $data = [
            [
                'customer_no' => 'C20260002',
                'innovation_subject' => '广州某某创新研究院',
                'innovation_subject_en' => 'Guangzhou XXX Innovation Research Institute',
                'credit_code' => '91440100MA5DQWXY34',
                'legal_representative' => '王五',
                'company_contact' => '赵六',
                'customer_level' => 'B',
                'customer_scale' => '小微企业',
                'creator' => 'GYZ',
                'price_index' => '70.00',
                'innovation_index' => '88.50',
                'contract_count' => 1,
                'latest_contract_date' => '2026-05-20',
                'remark' => '测试客户2',
            ],
            [
                'customer_no' => 'C20260003',
                'innovation_subject' => '北京某某数据服务有限公司',
                'innovation_subject_en' => 'Beijing XXX Data Service Co., Ltd.',
                'credit_code' => '91110000MA5DQWXY56',
                'legal_representative' => '孙七',
                'company_contact' => '周八',
                'customer_level' => 'C',
                'customer_scale' => '大型企业',
                'creator' => 'GYZ',
                'price_index' => '95.00',
                'innovation_index' => '99.50',
                'contract_count' => 10,
                'latest_contract_date' => '2026-06-15',
                'remark' => '测试客户3',
            ],
            [
                'customer_no' => 'C2026060004',
                'innovation_subject' => '北京某某科技有限公司',
                'innovation_subject_en' => 'Beijing XXX Technology Co., Ltd.',
                'credit_code' => '91110100MA5CXTYU12',
                'legal_representative' => '赵一',
                'company_contact' => '钱二',
                'customer_level' => 'A',
                'customer_scale' => '规模以上企业',
                'creator' => 'admin',
                'price_index' => '0.00',
                'innovation_index' => '0.00',
                'contract_count' => 0,
                'latest_contract_date' => '2026-05-10',
                'remark' => '重点客户',
            ],
            [
                'customer_no' => 'C2026060005',
                'innovation_subject' => '杭州某某网络技术有限公司',
                'innovation_subject_en' => 'Hangzhou XXX Network Technology Co., Ltd.',
                'credit_code' => '91330100MA5CXTZV34',
                'legal_representative' => '孙二',
                'company_contact' => '李三',
                'customer_level' => 'B',
                'customer_scale' => '科技型中小企业',
                'creator' => 'admin',
                'price_index' => '0.00',
                'innovation_index' => '0.00',
                'contract_count' => 0,
                'latest_contract_date' => '2026-04-20',
                'remark' => '优质客户',
            ],
            [
                'customer_no' => 'C20260003',
                'innovation_subject' => '深圳某某创新科技有限公司',
                'innovation_subject_en' => 'Shenzhen XXX Innovation Technology Co., Ltd.',
                'credit_code' => '91440300MA5DQPXY67',
                'legal_representative' => '李四',
                'company_contact' => '张经理',
                'customer_level' => 'A',
                'customer_scale' => '科技型中小企业',
                'creator' => 'admin',
                'price_index' => '85.00',
                'innovation_index' => '92.00',
                'contract_count' => 2,
                'latest_contract_date' => '2026-06-15',
                'remark' => '重点客户',
            ],
            [
                'customer_no' => 'C20260004',
                'innovation_subject' => '广州某智造科技股份有限公司',
                'innovation_subject_en' => 'Guangzhou MZ Zhizao Technology Co., Ltd.',
                'credit_code' => '91440101MA5CXTYU89',
                'legal_representative' => '王二',
                'company_contact' => '陈总',
                'customer_level' => 'A',
                'customer_scale' => '规模以上企业',
                'creator' => 'admin',
                'price_index' => '88.00',
                'innovation_index' => '95.00',
                'contract_count' => 5,
                'latest_contract_date' => '2026-06-20',
                'remark' => '重点扶持企业',
            ],
            [
                'customer_no' => 'C20260005',
                'innovation_subject' => '东莞某精密机械有限公司',
                'innovation_subject_en' => 'Dongguan MZ Precision Machinery Co., Ltd.',
                'credit_code' => '91441900MA5CYHZV12',
                'legal_representative' => '赵六',
                'company_contact' => '刘经理',
                'customer_level' => 'B',
                'customer_scale' => '规模以上企业',
                'creator' => 'admin',
                'price_index' => '72.00',
                'innovation_index' => '80.00',
                'contract_count' => 3,
                'latest_contract_date' => '2026-06-10',
                'remark' => '优质客户',
            ],
            [
                'customer_no' => 'C20260006',
                'innovation_subject' => '佛山某新材料研究院有限公司',
                'innovation_subject_en' => 'Foshan MZ New Materials Research Institute Co., Ltd.',
                'credit_code' => '91440605MA5CZABW34',
                'legal_representative' => '孙七',
                'company_contact' => '周高工',
                'customer_level' => 'A',
                'customer_scale' => '科技型中小企业',
                'creator' => 'admin',
                'price_index' => '90.00',
                'innovation_index' => '97.00',
                'contract_count' => 4,
                'latest_contract_date' => '2026-06-18',
                'remark' => '战略合作客户',
            ],
            [
                'customer_no' => 'C20260007',
                'innovation_subject' => '珠海某海洋工程装备有限公司',
                'innovation_subject_en' => 'Zhuhai MZ Ocean Engineering Equipment Co., Ltd.',
                'credit_code' => '91440400MA5CZBCY56',
                'legal_representative' => '钱八',
                'company_contact' => '郑总工',
                'customer_level' => 'B',
                'customer_scale' => '规模以上企业',
                'creator' => 'admin',
                'price_index' => '75.00',
                'innovation_index' => '82.00',
                'contract_count' => 2,
                'latest_contract_date' => '2026-06-05',
                'remark' => '潜力客户',
            ],
        ];

        foreach ($data as $item) {
            CustomerBasic::create($item);
        }
    }
}
